# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TemporalTestRepo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:event, primary_key: false) do
      add(:id, :bigint, null: false, primary_key: true)
      add(:name, :text)
      add(:created, :utc_datetime_usec)
    end

    create table(:member, primary_key: false) do
      add(:id, :bigint, null: false)
      add(:email, :citext)
      add(:valid_at, :tstzrange, null: false)
    end

    execute("ALTER TABLE \"member\" ADD PRIMARY KEY (id, valid_at WITHOUT OVERLAPS)")

    execute(
      "ALTER TABLE \"member\" ADD CONSTRAINT \"member_unique_email_index\" EXCLUDE USING gist ((lower(email::text)) WITH =, valid_at WITH &&)"
    )

    create table(:subscription, primary_key: false) do
      add(:id, :bigint, null: false)
      add(:tier, :text)
      add(:tier_id, :bigint)
      add(:seats, :bigint, default: 0)
      add(:activated_at, :utc_datetime_usec)
      add(:valid_at, :tstzrange, null: false)
    end

    execute("ALTER TABLE \"subscription\" ADD PRIMARY KEY (id, valid_at WITHOUT OVERLAPS)")

    alter table(:subscription) do
      add(:recorded_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:tier, primary_key: false) do
      add(:id, :bigint, null: false)
      add(:name, :text)
      add(:valid_at, :tstzrange, null: false)
    end

    execute("ALTER TABLE \"tier\" ADD PRIMARY KEY (id, valid_at WITHOUT OVERLAPS)")

    execute(
      "ALTER TABLE \"subscription\" ADD CONSTRAINT subscription_tier_id_fkey FOREIGN KEY (tier_id, PERIOD valid_at) REFERENCES \"public\".\"tier\" (id, PERIOD valid_at)"
    )
  end

  def down do
    execute("ALTER TABLE \"subscription\" DROP CONSTRAINT subscription_tier_id_fkey")

    drop(table(:tier))

    alter table(:subscription) do
      remove(:recorded_at)
    end

    drop(table(:subscription))

    execute("ALTER TABLE \"member\" DROP CONSTRAINT IF EXISTS \"member_unique_email_index\"")

    drop(table(:member))

    drop(table(:event))
  end
end
