# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TemporalTestRepo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS temporal_scoped")

    create table(:scoped_plan, primary_key: false, prefix: "temporal_scoped") do
      add(:id, :bigint, null: false)
      add(:name, :text)
      add(:valid_at, :tstzrange, null: false)
    end

    execute(
      "ALTER TABLE \"temporal_scoped\".\"scoped_plan\" ADD PRIMARY KEY (id, valid_at WITHOUT OVERLAPS)"
    )
  end

  def down do
    drop(table(:scoped_plan, prefix: "temporal_scoped"))
  end
end
