defmodule AshPostgres.TestRepo.TenantMigrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:multitenant_posts, prefix: prefix()) do
      modify :id, :binary_id, default: nil
    end
  end

  def down do
    alter table(:multitenant_posts, prefix: prefix()) do
      modify :id, :binary_id, default: fragment("uuid_generate_v4()")
    end
  end
end