defmodule AshPostgres.TestRepo.TenantMigrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:multitenant_posts, "multitenant_posts_org_id_fkey")

    alter table(:multitenant_posts, prefix: prefix()) do
      modify :org_id,
             references(:multitenant_orgs,
               column: :id,
               prefix: "public",
               name: "multitenant_posts_org_id_fkey",
               type: :uuid
             )
    end
  end

  def down do
    drop constraint(:multitenant_posts, "multitenant_posts_org_id_fkey")

    alter table(:multitenant_posts, prefix: prefix()) do
      modify :org_id,
             references(:multitenant_orgs,
               column: :id,
               prefix: "public",
               name: "multitenant_posts_org_id_fkey",
               type: :uuid
             )
    end
  end
end