defmodule AshPostgres.TestRepo.TenantMigrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:multitenant_posts, prefix: prefix()) do
      add :user_id,
          references(:users,
            column: :id,
            prefix: "public",
            name: "multitenant_posts_user_id_fkey",
            type: :uuid
          )
    end
  end

  def down do
    drop constraint(:multitenant_posts, "multitenant_posts_user_id_fkey")

    alter table(:multitenant_posts, prefix: prefix()) do
      remove :user_id
    end
  end
end