# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs.contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.TenantMigrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:multitenant_posts, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text
      add :score, :integer
      add :rating, :decimal

      add :org_id,
          references(:multitenant_orgs,
            column: :id,
            prefix: "public",
            name: "multitenant_posts_org_id_fkey",
            type: :uuid
          )

      add :user_id,
          references(:users,
            column: :id,
            prefix: "public",
            name: "multitenant_posts_user_id_fkey",
            type: :uuid
          )
    end
  end

  def down do
    drop constraint(:multitenant_posts, "multitenant_posts_user_id_fkey")

    drop constraint(:multitenant_posts, "multitenant_posts_org_id_fkey")

    drop table(:multitenant_posts, prefix: prefix())
  end
end
