defmodule AshPostgres.TestRepo.TenantMigrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:composite_key, primary_key: false, prefix: prefix()) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:title, :text, null: false)

      add(
        :org_id,
        references(:multitenant_orgs,
          column: :id,
          prefix: "public",
          name: "composite_key_org_id_fkey",
          type: :uuid
        )
      )
    end
  end

  def down do
    drop(constraint(:composite_key, "composite_key_org_id_fkey"))

    drop(table(:composite_key, prefix: prefix()))
  end
end
