defmodule AshPostgres.TestRepo.TenantMigrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:composite_key, primary_key: false, prefix: prefix()) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:title, :text, null: false)
    end
  end

  def down do
    drop(table(:composite_key, prefix: prefix()))
  end
end
