# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

---
updates:
  - directory: /
    groups:
      all-dependencies:
        patterns:
          - '*'
    package-ecosystem: mix
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
version: 2
