# THIS FILE IS AUTOGENERATED USING `mix ash.formatter`
# DONT MODIFY IT BY HAND
locals_without_parens = [
  base_filter_sql: 1,
  create?: 1,
  foreign_key_names: 1,
  migrate?: 1,
  name: 1,
  on_delete: 1,
  on_update: 1,
  polymorphic?: 1,
  polymorphic_name: 1,
  polymorphic_on_delete: 1,
  polymorphic_on_update: 1,
  reference: 1,
  reference: 2,
  repo: 1,
  skip_unique_indexes: 1,
  table: 1,
  template: 1,
  unique_index_names: 1,
  update?: 1
]

[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  locals_without_parens: locals_without_parens,
  export: [
    locals_without_parens: locals_without_parens
  ]
]
