# THIS FILE IS AUTOGENERATED USING `mix ash.formatter`
# DONT MODIFY IT BY HAND
locals_without_parens = [
  base_filter_sql: 1,
  create?: 1,
  migrate?: 1,
  repo: 1,
  skip_unique_indexes: 1,
  table: 1,
  template: 1,
  update?: 1
]

[
  import_deps: [:ash],
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  locals_without_parens: locals_without_parens,
  export: [
    locals_without_parens: locals_without_parens
  ]
]
