# SPDX-FileCopyrightText: 2024 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.Temporal.PlainPrimaryKey do
  @moduledoc """
  Used when a temporal resource's table has a plain primary key instead of a
  `WITHOUT OVERLAPS` one, so it can't hold more than one version of a record.

  Migrations generated by AshPostgres before 2.14.1 only created the temporal primary key
  on PostgreSQL 19, and fell back to a plain one otherwise. See the temporal resources
  guide for how to fix the table.
  """

  use Splode.Error, fields: [:resource, :table], class: :framework

  def message(error) do
    "Temporal write to #{inspect(error.resource)} failed: the primary key of `#{error.table}` " <>
      "isn't `WITHOUT OVERLAPS`, so the table can't hold more than one version of a record. " <>
      "Migrations generated before AshPostgres 2.14.1 created a plain primary key on " <>
      "PostgreSQL 18. See the AshPostgres temporal resources guide to fix the table."
  end
end
