defmodule AshPostgres.DevTestRepo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:multitenant_orgs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:owner_id, :uuid)
    end

    create(
      unique_index(:multitenant_orgs, [:id, :name], name: "multitenant_orgs_unique_by_name_index")
    )
  end

  def down do
    drop_if_exists(
      unique_index(:multitenant_orgs, [:id, :name], name: "multitenant_orgs_unique_by_name_index")
    )

    drop(table(:multitenant_orgs))
  end
end
