# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.AddLastReadMessageToChats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chats) do
      add(
        :last_read_message_id,
        references(:messages,
          column: :id,
          name: "chats_last_read_message_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:chats, "chats_last_read_message_id_fkey"))

    alter table(:chats) do
      remove(:last_read_message_id)
    end
  end
end
