# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.AddReadingTimeCalculationFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comments) do
      add(:edited_duration, :bigint)
      add(:planned_duration, :bigint)
      add(:reading_time, :bigint)
      add(:version, :text)
      add(:status, :text)
    end

    alter table(:posts) do
      add(:base_reading_time, :bigint)
    end
  end

  def down do
    alter table(:posts) do
      remove(:base_reading_time)
    end

    alter table(:comments) do
      remove(:status)
      remove(:version)
      remove(:reading_time)
      remove(:planned_duration)
      remove(:edited_duration)
    end
  end
end
