# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources72 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:department_post_comments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:text, :text)
      add(:organization_id, :uuid)
      add(:department_id, :uuid)
      add(:post_id, :uuid)
    end

    create table(:department_posts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:department_post_comments) do
      modify(
        :post_id,
        references(:department_posts,
          column: :id,
          name: "department_post_comments_post_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:department_posts) do
      add(:name, :text)
      add(:organization_id, :uuid)
      add(:department_id, :uuid)
    end

    create(
      unique_index(:department_posts, [:organization_id, :department_id, :name],
        name: "department_posts_unique_name_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:department_posts, [:organization_id, :department_id, :name],
        name: "department_posts_unique_name_index"
      )
    )

    alter table(:department_posts) do
      remove(:department_id)
      remove(:organization_id)
      remove(:name)
    end

    drop(constraint(:department_post_comments, "department_post_comments_post_id_fkey"))

    alter table(:department_post_comments) do
      modify(:post_id, :uuid)
    end

    drop(table(:department_posts))

    drop(table(:department_post_comments))
  end
end
