# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.Pg18BuiltinUuidv7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:relationship_items) do
      modify(:id, :uuid, default: fragment("uuidv7()"))
    end

    alter table(:other_items) do
      modify(:id, :uuid, default: fragment("uuidv7()"))
    end

    alter table(:sub_items) do
      modify(:id, :uuid, default: fragment("uuidv7()"))
    end

    alter table(:items) do
      modify(:id, :uuid, default: fragment("uuidv7()"))
    end

    alter table(:containers) do
      modify(:id, :uuid, default: fragment("uuidv7()"))
    end
  end

  def down do
    alter table(:containers) do
      modify(:id, :uuid, default: fragment("uuid_generate_v7()"))
    end

    alter table(:items) do
      modify(:id, :uuid, default: fragment("uuid_generate_v7()"))
    end

    alter table(:sub_items) do
      modify(:id, :uuid, default: fragment("uuid_generate_v7()"))
    end

    alter table(:other_items) do
      modify(:id, :uuid, default: fragment("uuid_generate_v7()"))
    end

    alter table(:relationship_items) do
      modify(:id, :uuid, default: fragment("uuid_generate_v7()"))
    end
  end
end
