# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources74 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:two_hop_entries, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:bucket_id, :uuid)
    end

    create table(:two_hop_items, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:bucket_id, :uuid)

      add(
        :entry_id,
        references(:two_hop_entries,
          column: :id,
          name: "two_hop_items_entry_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:two_hop_buckets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:two_hop_entries) do
      modify(
        :bucket_id,
        references(:two_hop_buckets,
          column: :id,
          name: "two_hop_entries_bucket_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:two_hop_items) do
      modify(
        :bucket_id,
        references(:two_hop_buckets,
          column: :id,
          name: "two_hop_items_bucket_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:two_hop_buckets) do
      add(:name, :text)
    end
  end

  def down do
    alter table(:two_hop_buckets) do
      remove(:name)
    end

    drop(constraint(:two_hop_items, "two_hop_items_entry_id_fkey"))

    drop(constraint(:two_hop_items, "two_hop_items_bucket_id_fkey"))

    alter table(:two_hop_items) do
      modify(:bucket_id, :uuid)
    end

    drop(constraint(:two_hop_entries, "two_hop_entries_bucket_id_fkey"))

    alter table(:two_hop_entries) do
      modify(:bucket_id, :uuid)
    end

    drop(table(:two_hop_buckets))

    drop(table(:two_hop_items))

    drop(table(:two_hop_entries))
  end
end
