# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources27 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:post_links, ["source_post_id", "destination_post_id"],
        name: "post_links_unique_link_index"
      )
    )

    create(
      unique_index(:post_links, ["destination_post_id", "source_post_id"],
        name: "post_links_unique_link_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:post_links, ["destination_post_id", "source_post_id"],
        name: "post_links_unique_link_index"
      )
    )

    create(
      unique_index(:post_links, ["source_post_id", "destination_post_id"],
        name: "post_links_unique_link_index"
      )
    )
  end
end
