# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources31 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:multitenant_orgs) do
      add(
        :owner_id,
        references(:users,
          column: :id,
          name: "multitenant_orgs_owner_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:multitenant_orgs, "multitenant_orgs_owner_id_fkey"))

    alter table(:multitenant_orgs) do
      remove(:owner_id)
    end
  end
end
