# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources75 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sourced_fk_children, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:ref_parent, :uuid, null: false)
    end

    create table(:sourced_fk_parents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:sourced_fk_children) do
      modify(
        :ref_parent,
        references(:sourced_fk_parents,
          column: :id,
          name: "sourced_fk_children_ref_parent_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end
  end

  def down do
    drop(constraint(:sourced_fk_children, "sourced_fk_children_ref_parent_fkey"))

    alter table(:sourced_fk_children) do
      modify(:ref_parent, :uuid)
    end

    drop(table(:sourced_fk_parents))

    drop(table(:sourced_fk_children))
  end
end
