# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources76 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:member, primary_key: false) do
      add(:id, :bigint, null: false)
      add(:email, :citext)
      add(:valid_at, :tstzrange, null: false)
    end

    if repo().query!("SHOW server_version_num").rows |> hd() |> hd() |> String.to_integer() >=
         190_000 do
      execute("ALTER TABLE \"member\" ADD PRIMARY KEY (id, valid_at WITHOUT OVERLAPS)")
    else
      execute("ALTER TABLE \"member\" ADD PRIMARY KEY (id)")
    end

    if repo().query!("SHOW server_version_num").rows |> hd() |> hd() |> String.to_integer() >=
         190_000 do
      execute(
        "ALTER TABLE \"member\" ADD CONSTRAINT \"member_unique_email_index\" EXCLUDE USING gist ((lower(email::text)) WITH =, valid_at WITH &&)"
      )
    else
      create(unique_index(:member, [:email], name: "member_unique_email_index"))
    end
  end

  def down do
    if repo().query!("SHOW server_version_num").rows |> hd() |> hd() |> String.to_integer() >=
         190_000 do
      execute("ALTER TABLE \"member\" DROP CONSTRAINT IF EXISTS \"member_unique_email_index\"")
    else
      drop_if_exists(unique_index(:member, [:email], name: "member_unique_email_index"))
    end

    drop(table(:member))
  end
end
