# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources79 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:licence, primary_key: false) do
      add(:id, :bigint, null: false)
      add(:holder, :text)
      add(:valid_on, :daterange, null: false)
    end

    if repo().query!("SHOW server_version_num").rows |> hd() |> hd() |> String.to_integer() >=
         190_000 do
      execute("ALTER TABLE \"licence\" ADD PRIMARY KEY (id, valid_on WITHOUT OVERLAPS)")
    else
      execute("ALTER TABLE \"licence\" ADD PRIMARY KEY (id)")
    end

    create table(:shift, primary_key: false) do
      add(:id, :bigint, null: false)
      add(:holder, :text)
      add(:valid_during, :tsrange, null: false)
    end

    if repo().query!("SHOW server_version_num").rows |> hd() |> hd() |> String.to_integer() >=
         190_000 do
      execute("ALTER TABLE \"shift\" ADD PRIMARY KEY (id, valid_during WITHOUT OVERLAPS)")
    else
      execute("ALTER TABLE \"shift\" ADD PRIMARY KEY (id)")
    end
  end

  def down do
    drop(table(:shift))

    drop(table(:licence))
  end
end
