# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.LockKeyColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lock_key_columns, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :uuid)
      add(:stock, :bigint)
      add(:rank, :bigint)
      add(:shop_id, :uuid)
      add(:sku, :text)
      add(:barcode, :text)
      add(:serial, :text)
      add(:tag_text, :text)
      add(:tag, :text)
      add(:label, :text)
      add(:alias_name, :text)
      add(:handle, :text)
      add(:nickname, :text)
    end

    create(
      unique_index(:lock_key_columns, [:org_id, :handle],
        name: "lock_key_columns_unique_handle_index"
      )
    )

    create(
      unique_index(:lock_key_columns, [:org_id, :nickname],
        name: "lock_key_columns_unique_nickname_index",
        where: "((nickname IS NOT NULL))"
      )
    )

    create(index(:lock_key_columns, [:org_id, asc: :shop_id, desc: :sku], unique: true))

    create(index(:lock_key_columns, [:org_id, "barcode"], unique: true))

    create(index(:lock_key_columns, [:org_id, desc: "serial"], unique: true))

    create(index(:lock_key_columns, [:org_id, :tag], unique: true))

    create(
      index(:lock_key_columns, [:org_id, "lower(label)"],
        name: "lock_key_columns_lower_label_index",
        unique: true
      )
    )

    create(
      index(:lock_key_columns, [:org_id, :alias_name],
        unique: true,
        where: "alias_name IS NOT NULL"
      )
    )

    create(index(:lock_key_columns, [:org_id, desc: :rank]))
  end

  def down do
    drop_if_exists(index(:lock_key_columns, [:org_id, desc: :rank]))

    drop_if_exists(index(:lock_key_columns, [:org_id, :alias_name]))

    drop_if_exists(
      index(:lock_key_columns, [:org_id, "lower(label)"],
        name: "lock_key_columns_lower_label_index"
      )
    )

    drop_if_exists(index(:lock_key_columns, [:org_id, :tag]))

    drop_if_exists(index(:lock_key_columns, [:org_id, desc: "serial"]))

    drop_if_exists(index(:lock_key_columns, [:org_id, "barcode"]))

    drop_if_exists(index(:lock_key_columns, [:org_id, asc: :shop_id, desc: :sku]))

    drop_if_exists(
      unique_index(:lock_key_columns, [:org_id, :nickname],
        name: "lock_key_columns_unique_nickname_index"
      )
    )

    drop_if_exists(
      unique_index(:lock_key_columns, [:org_id, :handle],
        name: "lock_key_columns_unique_handle_index"
      )
    )

    drop(table(:lock_key_columns))
  end
end
