# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources72 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:comment_ratings, "comment_ratings_resource_id_fkey"))

    alter table(:comment_ratings) do
      modify(
        :resource_id,
        references(:comments, column: :id, name: "comment_ratings_resource_id_fkey", type: :uuid)
      )
    end

    drop(constraint(:post_ratings, "post_ratings_resource_id_fkey"))

    alter table(:post_ratings) do
      modify(
        :resource_id,
        references(:posts, column: :id, name: "post_ratings_resource_id_fkey", type: :uuid)
      )
    end

    drop(constraint(:post_labels, "post_labels_content_id_fkey"))

    alter table(:post_labels) do
      modify(
        :content_id,
        references(:posts, column: :id, name: "post_labels_content_id_fkey", type: :uuid)
      )
    end
  end

  def down do
    drop(constraint(:post_labels, "post_labels_content_id_fkey"))

    alter table(:post_labels) do
      modify(
        :content_id,
        references(:posts, column: :id, name: "post_labels_content_id_fkey", type: :uuid)
      )
    end

    drop(constraint(:post_ratings, "post_ratings_resource_id_fkey"))

    alter table(:post_ratings) do
      modify(
        :resource_id,
        references(:posts, column: :id, name: "post_ratings_resource_id_fkey", type: :uuid)
      )
    end

    drop(constraint(:comment_ratings, "comment_ratings_resource_id_fkey"))

    alter table(:comment_ratings) do
      modify(
        :resource_id,
        references(:comments, column: :id, name: "comment_ratings_resource_id_fkey", type: :uuid)
      )
    end
  end
end
