# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources71 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:bulk_upsert_parents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:number, :bigint, null: false)
      add(:name, :text, null: false)
    end

    create(
      unique_index(:bulk_upsert_parents, [:number],
        name: "bulk_upsert_parents_unique_number_index"
      )
    )

    create table(:bulk_upsert_children, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:number, :bigint, null: false)

      add(
        :parent_id,
        references(:bulk_upsert_parents,
          column: :id,
          name: "bulk_upsert_children_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:bulk_upsert_children, "bulk_upsert_children_parent_id_fkey"))

    drop(table(:bulk_upsert_children))

    drop_if_exists(
      unique_index(:bulk_upsert_parents, [:number],
        name: "bulk_upsert_parents_unique_number_index"
      )
    )

    drop(table(:bulk_upsert_parents))
  end
end
