defmodule AshPostgres.TestRepo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up() do
    create table(:multitenant_orgs, primary_key: false) do
      add(:id, :binary_id, null: true, default: fragment("uuid_generate_v4()"), primary_key: true)
      add(:name, :text, null: true, default: nil, primary_key: false)
    end
  end

  def down() do
    drop(table("multitenant_orgs"))
  end
end