defmodule AshPostgres.TestRepo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up() do
    create table(:posts, primary_key: false) do
      add(:id, :binary_id, null: true, default: fragment("uuid_generate_v4()"), primary_key: true)
      add(:title, :text, null: true, default: nil, primary_key: false)
      add(:score, :integer, null: true, default: nil, primary_key: false)
      add(:public, :boolean, null: true, default: nil, primary_key: false)
    end

    create table(:comments, primary_key: false) do
      add(:id, :binary_id, null: true, default: fragment("uuid_generate_v4()"), primary_key: true)
      add(:title, :text, null: true, default: nil, primary_key: false)

      add(:post_id, references("posts", type: :binary_id, column: :id),
        default: nil,
        primary_key: false
      )
    end
  end

  def down() do
    drop(table("comments"))

    drop(table("posts"))
  end
end