defmodule AshPostgres.TestRepo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:integer_posts, primary_key: false) do
      add :id, :serial, null: false, primary_key: true
      add :title, :text
    end
  end

  def down do
    drop table("integer_posts")
  end
end