defmodule AshPostgres.TestRepo.Migrations.MigrateResources14 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text

      add :org_id,
          references(:multitenant_orgs, column: :id, name: "users_org_id_fkey", type: :uuid)
    end
  end

  def down do
    drop constraint(:users, "users_org_id_fkey")

    drop table(:users)
  end
end