defmodule AshPostgres.TestRepo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comments) do
      add :likes, :integer
    end
  end

  def down do
    alter table(:comments) do
      remove :likes
    end
  end
end
