defmodule AshPostgres.TestRepo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comments) do
      add :author_id,
          references(:authors, column: :id, name: "comments_author_id_fkey", type: :uuid)
    end
  end

  def down do
    alter table(:comments) do
      remove :author_id
    end
  end
end