defmodule AshPostgres.TestRepo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :decimal, :decimal, default: 0
    end
  end

  def down do
    alter table(:posts) do
      remove :decimal
    end
  end
end