defmodule AshPostgres.TestRepo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute(
      "ALTER INDEX multitenant_orgs_unique_by_name_unique_index RENAME TO multitenant_orgs_unique_by_name_index"
    )
  end

  def down do
    execute(
      "ALTER INDEX multitenant_orgs_unique_by_name_index RENAME TO multitenant_orgs_unique_by_name_unique_index"
    )
  end
end