defmodule AshPostgres.TestRepo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      modify :id, :binary_id, default: nil
      add :type, :text, default: "sponsored"
    end

    alter table(:post_ratings) do
      modify :id, :binary_id, default: nil
    end

    alter table(:multitenant_orgs) do
      modify :id, :binary_id, default: nil
    end

    alter table(:comments) do
      modify :id, :binary_id, default: nil
    end

    alter table(:comment_ratings) do
      modify :id, :binary_id, default: nil
    end
  end

  def down do
    alter table(:comment_ratings) do
      modify :id, :binary_id, default: fragment("uuid_generate_v4()")
    end

    alter table(:comments) do
      modify :id, :binary_id, default: fragment("uuid_generate_v4()")
    end

    alter table(:multitenant_orgs) do
      modify :id, :binary_id, default: fragment("uuid_generate_v4()")
    end

    alter table(:post_ratings) do
      modify :id, :binary_id, default: fragment("uuid_generate_v4()")
    end

    alter table(:posts) do
      remove :type
      modify :id, :binary_id, default: fragment("uuid_generate_v4()")
    end
  end
end