defmodule AshPostgres.TestRepo.Migrations.MigrateResources15 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comments) do
      add :arbitrary_timestamp, :utc_datetime_usec
    end
  end

  def down do
    alter table(:comments) do
      remove :arbitrary_timestamp
    end
  end
end
