defmodule AshPostgres.TestRepo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :status_enum, :status
    end
  end

  def down do
    alter table(:posts) do
      remove :status_enum
    end
  end
end