defmodule AshPostgres.TestRepo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :uniq_one, :text
      add :uniq_two, :text
    end

    create unique_index(:posts, [:uniq_one, :uniq_two],
             where: "type = 'sponsored'",
             name: "posts_uniq_one_and_two_index"
           )
  end

  def down do
    drop_if_exists unique_index(:posts, [:uniq_one, :uniq_two],
                     name: "posts_uniq_one_and_two_index"
                   )

    alter table(:posts) do
      remove :uniq_two
      remove :uniq_one
    end
  end
end