defmodule AshPostgres.TestRepo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :uniq_custom_one, :text
      add :uniq_custom_two, :text
    end
  end

  def down do
    alter table(:posts) do
      remove :uniq_custom_two
      remove :uniq_custom_one
    end
  end
end