defmodule AshPostgres.TestRepo.Migrations.MigrateResources12 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      modify :composite_point, :custom_point
    end
  end

  def down do
    alter table(:posts) do
      modify :composite_point, :point
    end
  end
end