defmodule AshPostgres.TestRepo.Migrations.AddTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false
    end

    create unique_index(:tags, [:name], name: "tags_name_index")

    create table(:posts_tags, primary_key: false) do
      add :position, :bigint, null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "posts_tags_post_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "posts_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    create unique_index(:posts_tags, [:position, :post_id],
             name: "posts_tags_unique_position_per_post_index"
           )
  end

  def down do
    drop_if_exists unique_index(:posts_tags, [:position, :post_id],
                     name: "posts_tags_unique_position_per_post_index"
                   )

    drop constraint(:posts_tags, "posts_tags_post_id_fkey")

    drop constraint(:posts_tags, "posts_tags_tag_id_fkey")

    drop table(:posts_tags)

    drop_if_exists unique_index(:tags, [:name], name: "tags_name_index")

    drop table(:tags)
  end
end