# SPDX-FileCopyrightText: 2020 Zach Daniel
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources40 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add(:ltree_unescaped, :ltree)
      add(:ltree_escaped, :ltree)
    end
  end

  def down do
    alter table(:posts) do
      remove(:ltree_escaped)
      remove(:ltree_unescaped)
    end
  end
end
