# SPDX-FileCopyrightText: 2020 Zach Daniel
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.NoAttributesCalculationTest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      add(:key, :text)
      add(:value, :bigint)
    end
  end

  def down do
    alter table(:items) do
      remove(:value)
      remove(:key)
    end
  end
end
