defmodule AshPostgres.TestRepo.Migrations.MigrateResources15 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :list_containing_nils, {:array, :text}
    end
  end

  def down do
    alter table(:posts) do
      remove :list_containing_nils
    end
  end
end