# SPDX-FileCopyrightText: 2020 Zach Daniel
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources22 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      modify(:updated_at, :"timestamptz(6)")
      modify(:datetime, :"timestamptz(6)")
    end
  end

  def down do
    alter table(:posts) do
      modify(:datetime, :utc_datetime_usec)
      modify(:updated_at, :utc_datetime_usec)
    end
  end
end
