# SPDX-FileCopyrightText: 2020 Zach Daniel
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources32 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:multitenant_orgs) do
      modify(:owner_id, :uuid)
    end
  end

  def down do
    alter table(:multitenant_orgs) do
      modify(:owner_id, :text)
    end
  end
end
