defmodule AshPostgres.TestRepo.Migrations.MigrateResources28 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create(
      unique_index(:post_followers, ["follower_id", "post_id"],
        name: "post_followers_join_attributes_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:post_followers, ["follower_id", "post_id"],
        name: "post_followers_join_attributes_index"
      )
    )
  end
end
