defmodule AshPostgres.TestRepo.Migrations.MigrateResources36 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create(unique_index(:other_items, [:item_id], name: "other_items_unique_parent_index"))
  end

  def down do
    drop_if_exists(
      unique_index(:other_items, [:item_id], name: "other_items_unique_parent_index")
    )
  end
end
