defmodule AshPostgres.TestRepo.Migrations.MigrateResources22 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      modify(:datetime, :timestamptz)
    end
  end

  def down do
    alter table(:posts) do
      modify(:datetime, :utc_datetime_usec)
    end
  end
end
