defmodule AshPostgres.TestRepo.Migrations.MigrateResources42 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add(:limited_score, :bigint)
    end
  end

  def down do
    alter table(:posts) do
      remove(:limited_score)
    end
  end
end
