defmodule AshPostgres.TestRepo.Migrations.MigrateResources32 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:multitenant_orgs) do
      remove(:owner_id)
      add(:owner_id, :text)
    end
  end

  def down do
    alter table(:multitenant_orgs) do
      remove(:owner_id)
      add(:owner_id, :uuid)
    end
  end
end
