defmodule AshPostgres.TestRepo.Migrations.MigrateResources64 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:authors) do
      add(:identities, :jsonb)
      add(:preferences, {:array, :map})
    end
  end

  def down do
    alter table(:authors) do
      remove(:preferences)
      remove(:identities)
    end
  end
end
