defmodule AshPostgres.TestRepo.Migrations.MigrateResources56 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add(:is_special, :boolean, null: false, default: true)
    end
  end

  def down do
    alter table(:posts) do
      remove(:is_special)
    end
  end
end
