# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs.contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources67 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:items) do
      modify(:updated_at, :utc_datetime_usec, null: true)
      modify(:inserted_at, :utc_datetime_usec, null: true)
      add(:name, :text)
      add(:active, :boolean, default: false)
      add(:container_id, :uuid)
    end

    create table(:containers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:items) do
      modify(
        :container_id,
        references(:containers,
          column: :id,
          name: "items_container_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:items, "items_container_id_fkey"))

    alter table(:items) do
      modify(:container_id, :uuid)
    end

    drop(table(:containers))

    alter table(:items) do
      remove(:container_id)
      remove(:active)
      remove(:name)
      modify(:inserted_at, :utc_datetime_usec, null: false)
      modify(:updated_at, :utc_datetime_usec, null: false)
    end
  end
end
