defmodule AshPostgres.TestRepo.Migrations.MigrateResources52 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify(:role_list, {:array, :text}, null: true)
      modify(:role, :text, null: true)

      add(
        :org_id,
        references(:multitenant_orgs,
          column: :id,
          name: "users_org_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:users, "users_org_id_fkey"))

    alter table(:users) do
      remove(:org_id)
      modify(:role, :text, null: false)
      modify(:role_list, {:array, :text}, null: false)
    end
  end
end
