defmodule AshPostgres.TestRepo.Migrations.MigrateResources53 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:multitenant_named_orgs, primary_key: false) do
      add(:name, :text, null: false, primary_key: true)
    end
  end

  def down do
    drop(table(:multitenant_named_orgs))
  end
end
