defmodule AshPostgres.TestRepo.Migrations.MigrateResources55 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      modify(:model, :map, null: true)
    end
  end

  def down do
    alter table(:posts) do
      modify(:model, :map, null: false)
    end
  end
end
