# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs.contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources63 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:immutable_error_testers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:atom_value, :text, null: false)
      add(:string_value, :text, null: false)
      add(:integer_value, :bigint, null: false)
      add(:float_value, :float, null: false)
      add(:boolean_value, :boolean, null: false)
      add(:struct_value, :map, null: false)
      add(:uuid_value, :uuid, null: false)
      add(:date_value, :date, null: false)
      add(:time_value, :time, null: false)
      add(:ci_string_value, :citext, null: false)
      add(:naive_datetime_value, :naive_datetime, null: false)
      add(:utc_datetime_value, :utc_datetime, null: false)
      add(:timestamptz_value, :timestamptz, null: false)
      add(:string_array_value, {:array, :text}, null: false)
      add(:response_value, :integer, null: false)
      add(:nullable_string_value, :text)
    end
  end

  def down do
    drop(table(:immutable_error_testers))
  end
end
