defmodule AshPostgres.TestRepo.Migrations.MigrateResources66 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:meals, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
    end

    alter table(:meal_items) do
      add(
        :meal_id,
        references(:meals,
          column: :id,
          name: "meal_items_meal_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:meal_items, "meal_items_meal_id_fkey"))

    alter table(:meal_items) do
      remove(:meal_id)
    end

    drop(table(:meals))
  end
end
