defmodule AshPostgres.TestRepo.Migrations.MigrateResources61 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:authors) do
      add(:settings, :jsonb)
    end
  end

  def down do
    alter table(:authors) do
      remove(:settings)
    end
  end
end
