defmodule AshPostgres.TestRepo.Migrations.AddModelTupleToPost do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add(:model, :map, null: false)
    end
  end

  def down do
    alter table(:posts) do
      remove(:model)
    end
  end
end
