defmodule AshPostgres.TestRepo.Migrations.MigrateResources71 do
  @moduledoc """
  Adds the `embedded_array_companies` table and the `company_id` column on
  `embedded_array_estimates`. Other autogenerated changes for unrelated
  resources (interest/profile_interest schemas, classroom.public) were
  trimmed out because those tables already exist in the local test DB.
  """

  use Ecto.Migration

  def up do
    alter table(:embedded_array_estimates) do
      add(:company_id, :uuid)
    end

    create table(:embedded_array_companies, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
    end
  end

  def down do
    drop(table(:embedded_array_companies))

    alter table(:embedded_array_estimates) do
      remove(:company_id)
    end
  end
end
