defmodule AshPostgres.TestRepo.Migrations.MigrateResources70 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:classrooms, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:school_id, :uuid)
    end

    create table(:teachers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
    end

    create table(:classroom_teachers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:retired_at, :utc_datetime_usec)

      add(
        :classroom_id,
        references(:classrooms,
          column: :id,
          name: "classroom_teachers_classroom_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :teacher_id,
        references(:teachers,
          column: :id,
          name: "classroom_teachers_teacher_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:classroom_teachers, [:classroom_id, :teacher_id],
        name: "classroom_teachers_unique_classroom_teacher_index"
      )
    )

    create table(:schools, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:classrooms) do
      modify(
        :school_id,
        references(:schools,
          column: :id,
          name: "classrooms_school_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:schools) do
      add(:name, :text)
    end

    create table(:students, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)

      add(
        :classroom_id,
        references(:classrooms,
          column: :id,
          name: "students_classroom_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:students, "students_classroom_id_fkey"))

    drop(table(:students))

    alter table(:schools) do
      remove(:name)
    end

    drop(constraint(:classrooms, "classrooms_school_id_fkey"))

    alter table(:classrooms) do
      modify(:school_id, :uuid)
    end

    drop(table(:schools))

    drop_if_exists(
      unique_index(:classroom_teachers, [:classroom_id, :teacher_id],
        name: "classroom_teachers_unique_classroom_teacher_index"
      )
    )

    drop(constraint(:classroom_teachers, "classroom_teachers_classroom_id_fkey"))

    drop(constraint(:classroom_teachers, "classroom_teachers_teacher_id_fkey"))

    drop(table(:classroom_teachers))

    drop(table(:teachers))

    drop(table(:classrooms))
  end
end
