defmodule AshPostgres.TestRepo.Migrations.MigrateResources71 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:post_labels, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(
        :content_id,
        references(:posts, column: :id, name: "post_labels_content_id_fkey", type: :uuid),
        null: false
      )

      add(:label_id, :uuid, null: false)
    end

    create(index(:post_labels, [:label_id]))

    create(index(:post_labels, [:content_id]))

    create(
      unique_index(:post_labels, [:content_id, :label_id],
        name: "post_labels_unique_content_id_and_label_id_index"
      )
    )

    create table(:labels, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:post_labels) do
      modify(
        :label_id,
        references(:labels,
          column: :id,
          name: "post_labels_label_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    alter table(:labels) do
      add(:value, :text, null: false)
    end

    create(unique_index(:labels, [:value], name: "labels_unique_value_index"))
  end

  def down do
    drop_if_exists(unique_index(:labels, [:value], name: "labels_unique_value_index"))

    alter table(:labels) do
      remove(:value)
    end

    drop(constraint(:post_labels, "post_labels_label_id_fkey"))

    alter table(:post_labels) do
      modify(:label_id, :uuid)
    end

    drop(table(:labels))

    drop(constraint(:post_labels, "post_labels_content_id_fkey"))

    drop_if_exists(
      unique_index(:post_labels, [:content_id, :label_id],
        name: "post_labels_unique_content_id_and_label_id_index"
      )
    )

    drop_if_exists(index(:post_labels, [:content_id]))

    drop_if_exists(index(:post_labels, [:label_id]))

    drop(table(:post_labels))
  end
end
