# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.MigrateResources70 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:comment_likes, primary_key: false) do
      add(
        :author_id,
        references(:authors,
          column: :id,
          name: "comment_like_author_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all,
          on_update: :update_all
        ),
        primary_key: true,
        null: false
      )

      add(
        :comment_id,
        references(:comments,
          column: :id,
          name: "comment_like_comment_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all,
          on_update: :update_all
        ),
        primary_key: true,
        null: false
      )
    end
  end

  def down do
    drop(constraint(:comment_likes, "comment_like_author_fkey"))

    drop(constraint(:comment_likes, "comment_like_comment_fkey"))

    drop(table(:comment_likes))
  end
end
