defmodule AshPostgres.TestRepo.Migrations.AddKeywordMap do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add(:keyword_map, :map)
    end
  end

  def down do
    alter table(:posts) do
      remove(:keyword_map)
    end
  end
end
