defmodule AshPostgres.TestRepo.Migrations.AddTitleToTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tags) do
      add(:title, :text)
    end
  end

  def down do
    alter table(:tags) do
      remove(:title)
    end
  end
end
