# SPDX-FileCopyrightText: 2019 ash_postgres contributors <https://github.com/ash-project/ash_postgres/graphs/contributors>
#
# SPDX-License-Identifier: MIT

defmodule AshPostgres.TestRepo.Migrations.AddNotificationRecipients do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:notification_recipients, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:order, :bigint)

      add(
        :post_id,
        references(:posts,
          column: :id,
          name: "notification_recipients_post_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :comment_id,
        references(:comments,
          column: :id,
          name: "notification_recipients_comment_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "notification_recipients_user_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      add(
        :staff_group_id,
        references(:staff_group,
          column: :id,
          name: "notification_recipients_staff_group_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(
      unique_index(:notification_recipients, [:post_id, :user_id],
        name: "notification_recipients_post_user_index",
        where: "((post_id IS NOT NULL) AND (user_id IS NOT NULL))"
      )
    )
  end

  def down do
    drop(constraint(:notification_recipients, "notification_recipients_post_id_fkey"))

    drop(constraint(:notification_recipients, "notification_recipients_comment_id_fkey"))

    drop(constraint(:notification_recipients, "notification_recipients_user_id_fkey"))

    drop(constraint(:notification_recipients, "notification_recipients_staff_group_id_fkey"))

    drop_if_exists(
      unique_index(:notification_recipients, [:post_id, :user_id],
        name: "notification_recipients_post_user_index"
      )
    )

    drop(table(:notification_recipients))
  end
end
