defmodule AshPostgres.TestRepo.Migrations.MigrateResources70 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:rollback_children, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text, null: false)
      add(:rollback_parent_id, :uuid)
    end

    create table(:rollback_parents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:rollback_children) do
      modify(
        :rollback_parent_id,
        references(:rollback_parents,
          column: :id,
          name: "rollback_children_rollback_parent_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    alter table(:rollback_parents) do
      add(:name, :text, null: false)
    end
  end

  def down do
    alter table(:rollback_parents) do
      remove(:name)
    end

    drop(constraint(:rollback_children, "rollback_children_rollback_parent_id_fkey"))

    alter table(:rollback_children) do
      modify(:rollback_parent_id, :uuid)
    end

    drop(table(:rollback_parents))

    drop(table(:rollback_children))
  end
end
