defmodule AshPostgres.TestRepo.Migrations.TemporalMore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:subscription, primary_key: false) do
      add(:id, :bigint, null: false)
      add(:tier, :text)
      add(:tier_id, :bigint)
      add(:seats, :bigint, default: 0)
      add(:activated_at, :utc_datetime_usec)
      add(:valid_at, :tstzrange)
    end

    create table(:tier, primary_key: false) do
      add(:id, :bigint, null: false)
      add(:name, :text)
      add(:valid_at, :tstzrange)
    end

    create table(:event, primary_key: false) do
      add(:id, :bigint, null: false, primary_key: true)
      add(:name, :text)
      add(:created, :utc_datetime_usec)
    end

    if repo().query!("SHOW server_version_num").rows |> hd() |> hd() |> String.to_integer() >=
         190_000 do
      execute("ALTER TABLE \"tier\" ADD PRIMARY KEY (id, valid_at WITHOUT OVERLAPS)")
    else
      execute("ALTER TABLE \"tier\" ADD PRIMARY KEY (id)")
    end

    if repo().query!("SHOW server_version_num").rows |> hd() |> hd() |> String.to_integer() >=
         190_000 do
      execute("ALTER TABLE \"subscription\" ADD PRIMARY KEY (id, valid_at WITHOUT OVERLAPS)")
    else
      execute("ALTER TABLE \"subscription\" ADD PRIMARY KEY (id)")
    end

    if repo().query!("SHOW server_version_num").rows |> hd() |> hd() |> String.to_integer() >=
         190_000 do
      execute(
        "ALTER TABLE \"subscription\" ADD CONSTRAINT subscription_tier_id_fkey FOREIGN KEY (tier_id, PERIOD valid_at) REFERENCES \"public\".\"tier\" (id, PERIOD valid_at)"
      )
    end
  end

  def down do
    execute("ALTER TABLE \"subscription\" DROP CONSTRAINT subscription_tier_id_fkey")

    drop(table(:event))

    drop(table(:tier))

    drop(table(:subscription))
  end
end
