defmodule AshPostgres.TestRepo.Migrations.MigrateResources68 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:embedded_array_estimates, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:title, :text)
      add(:active, :boolean, default: true)
      add(:options, :jsonb)
    end
  end

  def down do
    drop(table(:embedded_array_estimates))
  end
end
