defmodule AshPostgres.TestRepo.Migrations.MigrateResources72 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:department_posts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:organization_id, :uuid)
      add(:department_id, :uuid)
    end

    create(
      unique_index(:department_posts, [:organization_id, :department_id, :name],
        name: "department_posts_unique_name_index"
      )
    )

    create table(:department_post_comments, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:text, :text)
      add(:organization_id, :uuid)
      add(:department_id, :uuid)

      add(
        :post_id,
        references(:department_posts,
          column: :id,
          name: "department_post_comments_post_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:department_post_comments, "department_post_comments_post_id_fkey"))

    drop(table(:department_post_comments))

    drop_if_exists(
      unique_index(:department_posts, [:organization_id, :department_id, :name],
        name: "department_posts_unique_name_index"
      )
    )

    drop(table(:department_posts))
  end
end
